replicaCount: 1

image:
  repository: ghcr.io/armanfeyzi/agentnet-web
  tag: "latest"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 3000

env:
  API_URL: http://agentnet-api.backend.svc.cluster.local:8000
  PORT: "3000"

ingress:
  enabled: false
  className: traefik
  annotations: {}
  hosts: []
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    memory: 256Mi
